{{ if .Values.clusterSecretTemplate.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.clusterSecretTemplate.configmapName}}
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubermatic-argocd-bridge
data:
  "{{ .Values.clusterSecretTemplate.configmapKey }}": |
  {{ .Values.clusterSecretTemplate.content | nindent 4 }}
{{ end }}